# Copyright 2021 - 2026 Universität Tübingen, DKFZ, EMBL, and Universität zu Köln
# for the German Human Genome-Phenome Archive (GHGA)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## creating building container
FROM python:3.13-slim-trixie AS builder
# update and install dependencies
RUN apt-get update && apt-get upgrade -y
RUN pip install build
# copy code
COPY . /service
WORKDIR /service
# build wheel
RUN python -m build

# creating running container
FROM python:3.13-slim-trixie
# update and install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# create new user first
RUN useradd --create-home appuser
# copy and install requirements and wheel
WORKDIR /service
COPY --from=builder /service/lock/requirements.txt /service
RUN pip install --no-cache-dir --no-deps -r requirements.txt && \
    rm requirements.txt
COPY --from=builder /service/dist/ /service
RUN pip install --no-cache-dir --no-deps *.whl && \
    rm *.whl
# switch to non-root user
WORKDIR /home/appuser
USER appuser
# set environment
ENV PYTHONUNBUFFERED=1

# run auth service
ENTRYPOINT ["opentelemetry-instrument", "auth-service"]
