#!/bin/bash
# install service in dev container

cd /workspace

# install in edit mode
# use-feature way of installing packages
# install with testing dependencies
pip install \
    -e \
    ".[all]"

if python scripts/create_dev_keys.py; then
    set -a
    . .devcontainer/auth_keys.env
    set +a
fi

# install pre-commit hooks to git:
pre-commit install
