#!/bin/bash
# install service in dev container

cd /workspace

# install in edit mode
# use-feature way of installing packages
# install with testing dependencies
pip install \
    -e \
    ".[all]"

python scripts/create_dev_keys.py
set -a
. .devcontainer/local.env
set +a

# install pre-commit hooks to git:
pre-commit install
