name: Check if the config schema and the example are up to date.

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - id: common
        uses: ghga-de/gh-action-common@v1.0.2

      - name: Check if config schema is up to date
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          # regenerate config schema:
          ./scripts/get_config_schema_and_example.py print-schema > config_schema_regen.json

          # compare with existing json:
          diff config_schema_regen.json config_schema.json

      - name: Check if config example is up to date
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          # regenerate config schema:
          ./scripts/get_config_schema_and_example.py print-example > example_config_regen.yaml

          # compare with existing yaml:
          diff example_config_regen.yaml example_config.yaml
